### ISSUE TITLE
Add SPM Support

### ISSUE THREAD

**Issue by GaneshMyNewCar** [ochococo/Insomnia#7]

**Comment by ochococo** [comment]
Done ✅

**Comment by uniqby** [comment]
when trying to add version 2.0.0
.../SourcePackages/checkouts/Insomnia/Package.swift: https://github.com/ochococo/Insomnia has no Package.swift manifest for version 2.0.0 in https://github.com/ochococo/Insomnia

but when adding branch master it's ok.

**Comment by ochococo** [comment]
@uniqby you are correct, forgot to release version for SPM. Will be added in tag 2.0.1, stay tuned. Thank you!

**Comment by ochococo** [comment]
Done.
